(function(){var h=true,i=null,l=false,m,n=this;
function o(a){var c=typeof a;if(c=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return c;var b=Object.prototype.toString.call(a);if(b=="[object Window]")return"object";if(b=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(b=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(c=="function"&&typeof a.call=="undefined")return"object";return c}function aa(a){var c=o(a);return c=="array"||c=="object"&&typeof a.length=="number"}function r(a){return typeof a=="string"}function ba(a){var c=typeof a;return c=="object"&&a!=i||c=="function"}function s(a){return a[ca]||(a[ca]=++da)}var ca="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),da=0;function ea(a,c){function b(){}b.prototype=c.prototype;a.G=c.prototype;a.prototype=new b};function fa(a){if(!ga.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ha,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(ia,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(ja,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(ka,"&quot;");return a}var ha=/&/g,ia=/</g,ja=/>/g,ka=/\"/g,ga=/[&<>\"]/;function t(a,c){if(a<c)return-1;else if(a>c)return 1;return 0};var u,v,x,y;function la(){return n.navigator?n.navigator.userAgent:i}y=x=v=u=l;var z;if(z=la()){var ma=n.navigator;u=z.indexOf("Opera")==0;v=!u&&z.indexOf("MSIE")!=-1;x=!u&&z.indexOf("WebKit")!=-1;y=!u&&!x&&ma.product=="Gecko"}var na=u,A=v,B=y,D=x,oa=n.navigator,pa=(oa&&oa.platform||"").indexOf("Mac")!=-1,E;
a:{var F="",G;if(na&&n.opera){var H=n.opera.version;F=typeof H=="function"?H():H}else{if(B)G=/rv\:([^\);]+)(\)|;)/;else if(A)G=/MSIE\s+([^\);]+)(\)|;)/;else if(D)G=/WebKit\/(\S+)/;if(G){var qa=G.exec(la());F=qa?qa[1]:""}}if(A){var I,ra=n.document;I=ra?ra.documentMode:undefined;if(I>parseFloat(F)){E=String(I);break a}}E=F}var sa={};
function J(a){var c;if(!(c=sa[a])){c=0;for(var b=String(E).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(b.length,d.length),f=0;c==0&&f<e;f++){var g=b[f]||"",j=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var C=k.exec(g)||["","",""],p=q.exec(j)||["","",""];if(C[0].length==0&&p[0].length==0)break;c=t(C[1].length==0?0:parseInt(C[1],10),p[1].length==0?0:parseInt(p[1],10))||t(C[2].length==0,p[2].length==
0)||t(C[2],p[2])}while(c==0)}c=sa[a]=c>=0}return c}var ta={};function K(){return ta[9]||(ta[9]=A&&!!document.documentMode&&document.documentMode>=9)};function ua(){if(va)this.q=Error().stack}var wa=0,va=l;m=ua.prototype;m.key=0;m.c=l;m.j=l;m.d=function(a,c,b,d,e,f){if(o(a)=="function")this.n=h;else if(a&&a.handleEvent&&o(a.handleEvent)=="function")this.n=l;else throw Error("Invalid listener argument");this.e=a;this.p=c;this.src=b;this.type=d;this.capture=!!e;this.m=f;this.j=l;this.key=++wa;this.c=l};m.handleEvent=function(a){if(this.n)return this.e.call(this.m||this.src,a);return this.e.handleEvent.call(this.e,a)};function xa(a,c){for(var b in a)c.call(void 0,a[b],b,a)}var ya=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function za(a){for(var c,b,d=1;d<arguments.length;d++){b=arguments[d];for(c in b)a[c]=b[c];for(var e=0;e<ya.length;e++){c=ya[e];if(Object.prototype.hasOwnProperty.call(b,c))a[c]=b[c]}}};!A||K();var Aa=!A||K(),Ba=A&&!J("8");!D||J("528");B&&J("1.9b")||A&&J("8")||na&&J("9.5")||D&&J("528");B&&!J("8")||A&&J("9");var L=Array.prototype,M=L.indexOf?function(a,c,b){return L.indexOf.call(a,c,b)}:function(a,c,b){b=b==i?0:b<0?Math.max(0,a.length+b):b;if(r(a)){if(!r(c)||c.length!=1)return-1;return a.indexOf(c,b)}for(;b<a.length;b++)if(b in a&&a[b]===c)return b;return-1},N=L.forEach?function(a,c,b){L.forEach.call(a,c,b)}:function(a,c,b){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&c.call(b,e[f],f,a)},Ca=L.map?function(a,c,b){return L.map.call(a,c,b)}:function(a,c,b){for(var d=a.length,e=Array(d),f=
r(a)?a.split(""):a,g=0;g<d;g++)if(g in f)e[g]=c.call(b,f[g],g,a);return e};function Da(a){var c=a.length;if(c>0){for(var b=Array(c),d=0;d<c;d++)b[d]=a[d];return b}return[]}function Ea(a,c,b){return arguments.length<=2?L.slice.call(a,c):L.slice.call(a,c,b)};function Fa(){if(Ga){this.q=Error().stack;s(this)}}var Ga=l;function O(a,c){this.type=a;this.currentTarget=this.target=c}O.prototype.i=l;O.prototype.k=l;O.prototype.F=h;O.prototype.preventDefault=function(){this.k=h;this.F=l};function Ha(a){Ha[" "](a);return a}Ha[" "]=function(){};function P(a,c){a&&this.d(a,c)}ea(P,O);m=P.prototype;m.target=i;m.relatedTarget=i;m.offsetX=0;m.offsetY=0;m.clientX=0;m.clientY=0;m.screenX=0;m.screenY=0;m.button=0;m.keyCode=0;m.charCode=0;m.ctrlKey=l;m.altKey=l;m.shiftKey=l;m.metaKey=l;m.D=l;m.l=i;
m.d=function(a,c){var b=this.type=a.type;O.call(this,b);this.target=a.target||a.srcElement;this.currentTarget=c;var d=a.relatedTarget;if(d){if(B){var e;a:{try{Ha(d.nodeName);e=h;break a}catch(f){}e=l}e||(d=i)}}else if(b=="mouseover")d=a.fromElement;else if(b=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=D||a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?
a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(b=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.D=pa?a.metaKey:a.ctrlKey;this.state=a.state;this.l=a;a.k&&this.preventDefault();delete this.i};
m.preventDefault=function(){P.G.preventDefault.call(this);var a=this.l;if(a.preventDefault)a.preventDefault();else{a.returnValue=l;if(Ba)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(c){}}};var Q={},R={},T={},Ia={};
function Ja(a,c,b,d,e){if(c)if(o(c)=="array"){for(var f=0;f<c.length;f++)Ja(a,c[f],b,d,e);return i}else{d=!!d;var g=R;c in g||(g[c]={a:0,b:0});g=g[c];if(!(d in g)){g[d]={a:0,b:0};g.a++}g=g[d];var j=s(a),k;g.b++;if(g[j]){k=g[j];for(f=0;f<k.length;f++){g=k[f];if(g.e==b&&g.m==e){if(g.c)break;return k[f].key}}}else{k=g[j]=[];g.a++}f=Ka();f.src=a;g=new ua;g.d(b,f,a,c,d,e);b=g.key;f.key=b;k.push(g);Q[b]=g;T[j]||(T[j]=[]);T[j].push(g);if(a.addEventListener){if(a==n||!a.r)a.addEventListener(c,f,d)}else a.attachEvent(La(c),
f);return b}else throw Error("Invalid event type");}function Ka(){var a=Ma,c=Aa?function(b){return a.call(c.src,c.key,b)}:function(b){b=a.call(c.src,c.key,b);if(!b)return b};return c}function Na(a,c,b,d){if(!d.f)if(d.o){for(var e=0,f=0;e<d.length;e++)if(d[e].c)d[e].p.src=i;else{if(e!=f)d[f]=d[e];f++}d.length=f;d.o=l;if(f==0){delete R[a][c][b];R[a][c].a--;if(R[a][c].a==0){delete R[a][c];R[a].a--}R[a].a==0&&delete R[a]}}}function La(a){if(a in Ia)return Ia[a];return Ia[a]="on"+a}
function Oa(a,c,b,d,e){var f=1;c=s(c);if(a[c]){a.b--;a=a[c];if(a.f)a.f++;else a.f=1;try{for(var g=a.length,j=0;j<g;j++){var k=a[j];if(k&&!k.c)f&=Pa(k,e)!==l}}finally{a.f--;Na(b,d,c,a)}}return Boolean(f)}
function Pa(a,c){if(a.j){var b=a.key;if(Q[b]){var d=Q[b];if(!d.c){var e=d.src,f=d.type,g=d.p,j=d.capture;if(e.removeEventListener){if(e==n||!e.r)e.removeEventListener(f,g,j)}else e.detachEvent&&e.detachEvent(La(f),g);e=s(e);if(T[e]){g=T[e];var k=M(g,d);k>=0&&L.splice.call(g,k,1);g.length==0&&delete T[e]}d.c=h;if(d=R[f][j][e]){d.o=h;Na(f,j,e,d)}delete Q[b]}}}return a.handleEvent(c)}
function Ma(a,c){if(!Q[a])return h;var b=Q[a],d=b.type,e=R;if(!(d in e))return h;e=e[d];var f,g;if(!Aa){var j;if(!(j=c))a:{j="window.event".split(".");for(var k=n;f=j.shift();)if(k[f]!=i)k=k[f];else{j=i;break a}j=k}f=j;j=h in e;k=l in e;if(j){if(f.keyCode<0||f.returnValue!=undefined)return h;a:{var q=l;if(f.keyCode==0)try{f.keyCode=-1;break a}catch(C){q=h}if(q||f.returnValue==undefined)f.returnValue=h}}q=new P;q.d(f,this);f=h;try{if(j){for(var p=[],S=q.currentTarget;S;S=S.parentNode)p.push(S);g=e[h];
g.b=g.a;for(var w=p.length-1;!q.i&&w>=0&&g.b;w--){q.currentTarget=p[w];f&=Oa(g,p[w],d,h,q)}if(k){g=e[l];g.b=g.a;for(w=0;!q.i&&w<p.length&&g.b;w++){q.currentTarget=p[w];f&=Oa(g,p[w],d,l,q)}}}else f=Pa(b,q)}finally{if(p)p.length=0}return f}d=new P(c,this);return f=Pa(b,d)};function Qa(a){Fa.call(this);this.t=a;this.u=[]}ea(Qa,Fa);var Ra=[];function U(a,c,b,d){if(o(b)!="array"){Ra[0]=b;b=Ra}for(var e=0;e<b.length;e++)a.u.push(Ja(c,b[e],d||a,l,a.t||a));return a}Qa.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Sa(a){this.g=a}
function Ta(a,c,b){switch(typeof c){case "string":Ua(c,b);break;case "number":b.push(isFinite(c)&&!isNaN(c)?c:"null");break;case "boolean":b.push(c);break;case "undefined":b.push("null");break;case "object":if(c==i){b.push("null");break}if(o(c)=="array"){var d=c.length;b.push("[");for(var e="",f=0;f<d;f++){b.push(e);e=c[f];Ta(a,a.g?a.g.call(c,String(f),e):e,b);e=","}b.push("]");break}b.push("{");d="";for(f in c)if(Object.prototype.hasOwnProperty.call(c,f)){e=c[f];if(typeof e!="function"){b.push(d);
Ua(f,b);b.push(":");Ta(a,a.g?a.g.call(c,f,e):e,b);d=","}}b.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof c);}}var Va={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},Wa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Ua(a,c){c.push('"',a.replace(Wa,function(b){if(b in Va)return Va[b];var d=b.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Va[b]=e+d.toString(16)}),'"')};var Xa=[{pattern:"[^#]+",subst:"http://docs.google.com/viewer?url=$0",conditions:[{type:0,regexp:"^https?://"},{type:0,regexp:"\\.(?:pdf|docx?|xlsx?|pptx?|pages|eps|ps|xps)(?:[?#]|$)"}]}],Ya=[{pattern:"[^#]+",subst:"http://docs.google.com/viewer?url=$0",conditions:[{type:0,regexp:"^https?://"},{type:0,regexp:"\\.(?:ai|psd|tiff?|dxf|ttf)(?:[?#]|$)"}]}],Za=[{pattern:"([\\?&])hl=\\w+",subst:"$1hl={lang}",conditions:[{type:0,regexp:"^https?://maps.google.[^/]+/maps"},{type:2,regexp:"^https?://www.google.com/calendar"}]}];
function $a(a){var c=[];if(a.documents)c=c.concat(Xa);if(a.images)c=c.concat(Ya);if(a.maps){var b=Za[0];c.push({pattern:b.pattern,subst:b.subst.replace("{lang}",a.maps_lang||""),conditions:b.conditions})}return c};function ab(a){a=a.className;return r(a)&&a.match(/\S+/g)||[]}function bb(a){for(var c=ab(a),b=Ea(arguments,1),d=c.length+b.length,e=0;e<b.length;e++)M(c,b[e])>=0||c.push(b[e]);a.className=c.join(" ");return c.length==d};var cb=!A||K();!B&&!A||A&&K()||B&&J("1.9.1");A&&J("9");function V(a){return r(a)?document.getElementById(a):a}function W(a,c){var b=c||document;if(b.querySelectorAll&&b.querySelector)b=b.querySelector("."+a);else{b=c||document;b=b.querySelectorAll&&b.querySelector?b.querySelectorAll("."+a):b.getElementsByClassName?b.getElementsByClassName(a):X(document,"*",a,c);b=b[0]}return b||i}
function X(a,c,b,d){a=d||a;c=c&&c!="*"?c.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(c||b))return a.querySelectorAll(c+(b?"."+b:""));if(b&&a.getElementsByClassName){a=a.getElementsByClassName(b);if(c){d={};for(var e=0,f=0,g;g=a[f];f++)if(c==g.nodeName)d[e++]=g;d.length=e;return d}else return a}a=a.getElementsByTagName(c||"*");if(b){d={};for(f=e=0;g=a[f];f++){c=g.className;if(typeof c.split=="function"&&M(c.split(/\s+/),b)>=0)d[e++]=g}d.length=e;return d}else return a}
function db(a,c){xa(c,function(b,d){if(d=="style")a.style.cssText=b;else if(d=="class")a.className=b;else if(d=="for")a.htmlFor=b;else if(d in eb)a.setAttribute(eb[d],b);else if(d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0)a.setAttribute(d,b);else a[d]=b})}var eb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Y(){var a=arguments,c=a[0],b=a[1];if(!cb&&b&&(b.name||b.type)){c=["<",c];b.name&&c.push(' name="',fa(b.name),'"');if(b.type){c.push(' type="',fa(b.type),'"');var d={};za(d,b);b=d;delete b.type}c.push(">");c=c.join("")}c=document.createElement(c);if(b)if(r(b))c.className=b;else o(b)=="array"?bb.apply(i,[c].concat(b)):db(c,b);a.length>2&&fb(document,c,a);return c}
function fb(a,c,b){function d(j){if(j)c.appendChild(r(j)?a.createTextNode(j):j)}for(var e=2;e<b.length;e++){var f=b[e];if(aa(f)&&!(ba(f)&&f.nodeType>0)){var g;a:{if(f&&typeof f.length=="number")if(ba(f)){g=typeof f.item=="function"||typeof f.item=="string";break a}else if(o(f)=="function"){g=typeof f.item=="function";break a}g=l}N(g?Da(f):f,d)}else d(f)}}function gb(a){for(var c;c=a.firstChild;)a.removeChild(c)}function hb(a){a&&a.parentNode&&a.parentNode.removeChild(a)}
function ib(a,c,b){if(!c&&!b)return i;var d=c?c.toUpperCase():i;return jb(a,function(e){var f;if(f=!d||e.nodeName==d)if(!(f=!b)){e=ab(e);f=M(e,b)>=0}return f})}function jb(a,c){for(var b=0;a;){if(c(a))return a;a=a.parentNode;b++}return i};function kb(){var a=i;try{a=JSON.parse(localStorage.linktweak_settings)}catch(c){}if(!a)try{var b=JSON.parse(localStorage.rewriterules||""),d=[],e;if(aa(b))for(var f=0;f<b.length;++f)if((e=b[f])&&e.cond&&e.from)d[d.length]={pattern:e.from,subst:e.to||"",conditions:[{type:0,regexp:e.cond}]};a={version:1,presets:{},rules:d}}catch(g){}this.h=a||{};a=V("presets");b=V("rewrite-rules");d=V("add-rule");e=V("save");f=V("reset");this.s=new Qa(this);U(U(U(U(U(U(this.s,a,"change",this.v),b,"click",this.B),b,
"change",this.w),d,"click",this.z),e,"click",this.C),f,"click",this.A);lb(this)}var mb=[{label:"Link url is matched with",value:0},{label:"Link url is not matched with",value:1},{label:"Page url is matched with",value:2},{label:"Page url is not matched with",value:3}];m=kb.prototype;m.v=function(){nb(this);Z(h)};
m.B=function(a){var c=ib(a.target,i,"rule"),b=ib(a.target,"a");if(b){var d=(/#(.+)/.exec(b)||[])[1];if(d=="add-condition"){W("rule-conditions",c).appendChild(ob(this,l));a.preventDefault()}else if(d=="delete-condition"){c=ib(b,i,"rule-condition");hb(c);Z(h);a.preventDefault()}else if(d=="delete-rule"){hb(c);Z(h);a.preventDefault()}}};m.w=function(){Z(h)};m.z=function(a){a.preventDefault();V("rewrite-rules").appendChild($(this,l))};
m.C=function(){var a={version:1,presets:pb(),rules:qb(this)},c=localStorage,b=[];Ta(new Sa(void 0),a,b);c.linktweak_settings=b.join("");this.h=a;Z(l)};m.A=function(){lb(this)};
function $(a,c,b){var d=Y("div","rule");b=b||{};if(c)d.className+=" rule-preset";else d.appendChild(Y("div","rule-delete",Y("a",{href:"#delete-rule"},"Delete this rule")));var e=Y("input",{"class":"rule-pattern",value:b.pattern||""}),f=Y("input",{"class":"rule-substitution",value:b.subst||""});d.appendChild(Y("div","rule-replacement",Y("div","rule-label","Rewrite pattern:"),Y("div","rule-value",e),Y("div","rule-label","Substitution:"),Y("div","rule-value",f)));d.appendChild(Y("div","rule-conditions-label",
"Conditions:"));var g=Y("div","rule-conditions");N(b.conditions||[],function(j){g.appendChild(ob(this,c,j))},a);!c&&g.childNodes.length<=0&&g.appendChild(ob(a,l));d.appendChild(g);if(c){e.disabled="disabled";f.disabled="disabled"}else d.appendChild(Y("div","rule-add-condition",Y("a",{href:"#add-condition"},"Add condition")));return d}
function ob(a,c,b){a=Ca(mb,function(e){return Y("option",{value:e.value},e.label)},a);a=Y("select","rule-condition-type",a);var d=Y("input",{type:"text","class":"rule-condition-regexp"});if(b){a.value=b.type||0;d.value=b.regexp||""}b=Y("div","rule-condition",a,d);if(c){a.disabled="disabled";d.disabled="disabled"}else b.appendChild(Y("a",{href:"#delete-condition","class":"rule-condition-delete"},"\u00d7"));return b}
function nb(a){var c=X(document,"div","rule-preset",V("rewrite-rules"));N(c,function(d){hb(d)},a);c=$a(pb());var b=document.createDocumentFragment();N(c,function(d){b.appendChild($(this,h,d))},a);a=V("rewrite-rules");a.insertBefore(b,a.firstChild)}
function lb(a){var c=V("rewrite-rules");gb(c);var b=a.h.presets||{};V("preset-documents").checked=!!b.documents;V("preset-images").checked=!!b.images;V("preset-maps").checked=!!b.maps;V("preset-maps-lang").value=b.maps_lang||"";nb(a);b=a.h.rules||[];if(b.length<=0)c.appendChild($(a,l));else{var d=document.createDocumentFragment();N(b,function(e){d.appendChild($(this,l,e))},a);c.appendChild(d)}Z(l)}
function pb(){return{documents:!!V("preset-documents").checked,images:!!V("preset-images").checked,maps:!!V("preset-maps").checked,maps_lang:V("preset-maps-lang").value}}function qb(a){var c=X(document,"div","rule",V("rewrite-rules")),b=[];N(c,function(d){if(d.className.indexOf("rule-preset")<0){var e=W("rule-pattern",d),f=W("rule-substitution",d);if(e&&e.value&&f&&f.value){var g={};g.pattern=e.value;g.subst=f.value;g.conditions=rb(this,d);d=g}else d=i;d&&b.push(d)}},a);return b}
function rb(a,c){var b=X(document,"div","rule-condition",c),d=[];N(b,function(e){var f=W("rule-condition-type",e);e=W("rule-condition-regexp",e);f&&e&&d.push({type:f.value,regexp:e.value})},a);return d}function Z(a){a=a?"":"disabled";V("save").disabled=a;V("reset").disabled=a}new kb;})();
